package me.gavin.db.dao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import me.gavin.app.Account;
import me.gavin.app.Task;

import me.gavin.db.dao.AccountDao;
import me.gavin.db.dao.TaskDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig accountDaoConfig;
    private final DaoConfig taskDaoConfig;

    private final AccountDao accountDao;
    private final TaskDao taskDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        accountDaoConfig = daoConfigMap.get(AccountDao.class).clone();
        accountDaoConfig.initIdentityScope(type);

        taskDaoConfig = daoConfigMap.get(TaskDao.class).clone();
        taskDaoConfig.initIdentityScope(type);

        accountDao = new AccountDao(accountDaoConfig, this);
        taskDao = new TaskDao(taskDaoConfig, this);

        registerDao(Account.class, accountDao);
        registerDao(Task.class, taskDao);
    }
    
    public void clear() {
        accountDaoConfig.clearIdentityScope();
        taskDaoConfig.clearIdentityScope();
    }

    public AccountDao getAccountDao() {
        return accountDao;
    }

    public TaskDao getTaskDao() {
        return taskDao;
    }

}
